# Generated by Django 5.0.6 on 2024-06-12 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpotifyToken",
        ),
    ]
